@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0

class ClinicalAnalysisLaboratory{
    -idLaboratory
    -name
    -address
    -phoneNumber
    -tin
    -testType
}


class Employee{
    -name
    -function
    -phoneNumber
    -email
    -address
}

class Platform{
    -designation
}

class Administrator{
    -idEmployee
    -soc
}

class ParametersCategory{
    -code
    -name
}


ParametersCategory "*" -- "1" Administrator : created by >
Administrator "1" -- "*" Employee : is >
ClinicalAnalysisLaboratory "1" -- "*" ParametersCategory : adopts >
Employee "*" -- "1" Platform : uses >


@enduml