@startuml
autonumber
'hide footbox


participant ":CreateReportUI" as UI
participant ":CreateReportController" as CTRL
participant ":Company" as _APP
participant ":TestStore" as PCS
participant ":TestMapper" as PM


activate UI
UI -> CTRL : trDto = getLisfOfTests()
activate CTRL
CTRL -> _APP : trStore = getTestStore()
activate _APP
deactivate _APP
CTRL -> PCS : checkState("ANALYZED")
|||
activate PCS
CTRL -> PCS : tr = getLisfOfTests()
|||
deactivate PCS
CTRL -> PM : trDto = toDto(tr)
activate PM
deactivate PM

deactivate CTRL
deactivate UI





@enduml