@startuml
autonumber
actor "Clinical Chemistry Technologist" as LC

activate LC


LC -> ":System" : requests to see the historical tests of a client
activate ":System"

":System" --> LC : asks to choose the order of the client list (TIN or Name)
deactivate ":System"

loop until the actor decides to stop
LC -> ":System" : chooses the order
activate ":System"

":System" --> LC : shows the clients list and asks to select one
deactivate ":System"

loop until the actor changes the order of the list or decides to stop
LC -> ":System" : chooses a client
activate ":System"

loop until the actor changes client or decides to stop
    ":System" --> LC : shows the test list from that client with the "VALIDATED" state and asks to select one
    deactivate ":System"

    LC -> ":System" : chooses a test
    activate ":System"
    ":System" --> LC : shows the test's information and results
    deactivate ":System"
end loop
end loop
end loop
deactivate LC
@enduml