@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0


class Company{
-chemicalLab
}

class Client{
-citizenCardNumber
-healthCareService
-tin
-birthdate
-name
-phoneNumber
-sex
}

Company "1" -- "*" Client : can access the information of >


@enduml