@startuml
autonumber
actor "Administrator" as ADM

activate ADM
ADM -> ":System" : asks to create a new parameter
activate ":System"
":System" --> ADM : requests authetication
deactivate

ADM -> ":System" : introduces data
activate ":System"
":System" --> ADM : requests data (code,name,description)
deactivate ":System"

ADM -> ":System" : types requested data
activate ":System"
":System" --> ADM : shows parameter categories list and ask to select one
deactivate ":System"

ADM -> ":System" : selects a parameter category
activate ":System"
":System" --> ADM : shows all data and requests confirmation
deactivate ":System"

ADM -> ":System" : confirms the data
activate ":System"
":System" --> ADM : informs operation success
deactivate ":System"

deactivate ADM

@enduml